language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

addons:
  code_climate:
    repo_token: 4bc7c59eaf4c71eeca0acba679de34634ee069273c7811c99102c3a2872fbcd0

install:
  - composer install

script: vendor/bin/phpunit --coverage-clover build/logs/clover.xml
